db: 
  type: 'postgres'
  host: 'localhost'
  port: 5432
  username: 'postgres'
  password: 'postgres'
  database: 'postgres'
  synchronize: true
  autoLoadEntities: true

jwt: 
  secret: "ASDSFJK2343SAD"